name: My First Workflow

on: push 

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github action"

        - name: List files available in this repo
          run: ls

        - name: Read the files of this repo
          run: cat main.tf
          