name: Cowsay

on: 
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Generate ASCII Artwork
            run: |
            apt-get install cowsay -y
            cowsay -f dragon "run for a dragon" >> dragon.txt 
            grep -i "dragon" dragon.txt
            cat dragon.txt
            ls -lrat